package Locations.Dungeon.DungeonParts;

import Creatures.GodCreature;
import Creatures.Player;
import Things.Dungeon.DungeonWall;

public class DungeonPartClear extends PartDungeon implements DungeonPart {

    public DungeonPartClear(Player player){
        super(player);
    }

    public DungeonPartClear(){
        super();
    }
    @Override
    public GodCreature[][] getWay() {
        lower = new GodCreature[][]{
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()},
                {DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance(), DungeonWall.getInstance()}
        };
        return lower;
    }
}
